const ACTIONS = {
    INCREMENT: "INCREMENT",
    DECREMENT: "DECREMENT",
    GET_EVENT: "GET_EVENT",
    GET_EVENTS: "GET_EVENTS",
    ADD_EVENT: "ADD_EVENT",
    DELETE_EVENT: "DELETE_EVENT"
};

export default ACTIONS;