const ACTIONS = {
    GET_IMAGES: "GET_IMAGES",
    ADD_IMAGE: "ADD_IMAGE",
    DELETE_IMAGE: "DELETE_IMAGE",
    EDIT_ALT_IMAGE: "EDIT_ALT_IMAGE",
    RESET_IMAGE_UPLOAD: "RESET_IMAGE_UPLOAD"
};

export default ACTIONS;