const ACTIONS = {
    GET_RECOMMENDATIONS: "GET_RECOMMENDATIONS",
    ADD_RECOMMENDATION: "ADD_RECOMMENDATION",
    UPDATE_RECOMMENDATION: "UPDATE_RECOMMENDATION",
    DELETE_RECOMMENDATION: "DELETE_RECOMMENDATION",
    PATCH_RECOMMENDATION: "PATCH_RECOMMENDATION"
};

export default ACTIONS;